version: '3'
services:
  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && rails db:create && rails db:migrate && rails db:seed && rails server -b 0.0.0.0"
    volumes:
      - ".:/myapp"
    ports:
      - "3000:3000"
